import { ArrowUp, BookOpen, MessageSquareText, Square } from "lucide-react";
import { Fragment, useRef, useState } from "react";
import { Link } from "react-router-dom";
import { Page, useMeta } from "../components/AppShell.tsx";
import { useRegSheet } from "../components/RegSheet.tsx";
import { Badge, Card, Empty } from "../components/ui/index.tsx";
import { ApiError, streamPost } from "../lib/api.ts";
import { cx } from "../lib/format.ts";

interface Source {
  n: number;
  kind: "eccn" | "section";
  ref: string;
  cite: string;
  sectionId: string | null;
  preview: string;
}
interface Msg {
  role: "user" | "assistant";
  content: string;
  sources?: Source[];
  error?: string;
  streaming?: boolean;
}

const EXAMPLES = [
  "When does US de minimis use a 10% threshold instead of 25%?",
  "Which license exceptions can be used for items controlled only for NS reasons to Country Group B?",
  "一般国向けの16の項（1）の貨物について、通常兵器キャッチオールの需要者要件はどう定められていますか？",
  "What does §744.21 require for military end users in China?",
];

export function AskPage() {
  const meta = useMeta();
  const open = useRegSheet();
  const [msgs, setMsgs] = useState<Msg[]>([]);
  const [input, setInput] = useState("");
  const abort = useRef<AbortController | null>(null);
  const bottom = useRef<HTMLDivElement>(null);
  const busy = msgs.some((m) => m.streaming);

  const ask = async (q: string) => {
    if (!q.trim() || busy) return;
    const history = msgs.filter((m) => !m.error).map((m) => ({ role: m.role, content: m.content }));
    setMsgs((m) => [...m, { role: "user", content: q }, { role: "assistant", content: "", streaming: true }]);
    setInput("");
    const ctrl = new AbortController();
    abort.current = ctrl;
    const patch = (fn: (m: Msg) => Msg) => setMsgs((all) => all.map((m, i) => (i === all.length - 1 ? fn(m) : m)));
    try {
      await streamPost(
        "/ai/ask",
        { question: q, history: history.slice(-10) },
        (ev, data) => {
          if (ev === "sources") patch((m) => ({ ...m, sources: data as Source[] }));
          if (ev === "delta") {
            patch((m) => ({ ...m, content: m.content + (data as string) }));
            bottom.current?.scrollIntoView({ block: "end" });
          }
          if (ev === "error") patch((m) => ({ ...m, error: (data as { message: string }).message }));
        },
        ctrl.signal,
      );
    } catch (e) {
      if ((e as Error).name !== "AbortError") patch((m) => ({ ...m, error: e instanceof ApiError ? e.message : String(e) }));
    } finally {
      patch((m) => ({ ...m, streaming: false }));
    }
  };

  const openSource = (s: Source) => (s.kind === "eccn" ? open({ kind: "eccn", id: s.ref }) : s.sectionId && open({ kind: "section", id: s.sectionId, label: s.cite }));

  if (meta.data && !meta.data.settings.aiConfigured)
    return (
      <Page>
        <Card>
          <Empty icon={<MessageSquareText className="size-5" />} title="Ask the regulations needs an API key">
            Answers are generated by Claude from passages Kanmon retrieves from its own copy of the EAR and Japanese law, and every statement is cited. Add a key in{" "}
            <Link to="/settings" className="text-accent-text hover:underline">
              Settings
            </Link>
            . You can still search the{" "}
            <Link to="/regulations/library" className="text-accent-text hover:underline">
              regulation library
            </Link>{" "}
            without one.
          </Empty>
        </Card>
      </Page>
    );

  return (
    <div className="flex h-[calc(100vh-0px)] flex-col">
      <div className="scroll-thin flex-1 overflow-y-auto">
        <div className="mx-auto max-w-[820px] px-4 py-8 sm:px-8">
          {msgs.length === 0 ? (
            <div className="pt-[8vh]">
              <h1 className="text-[24px] font-semibold tracking-tight">Ask the regulations</h1>
              <p className="mt-2 max-w-xl text-[13.5px] text-fg-2">
                Questions are answered only from passages retrieved from the current EAR (15 CFR 730–774), the Commerce Control List and Japan’s FEFTA regime. Each statement cites its source; click a citation to read the provision.
              </p>
              <div className="mt-6 grid gap-2 sm:grid-cols-2">
                {EXAMPLES.map((e) => (
                  <button key={e} onClick={() => ask(e)} className="rounded-xl border border-line bg-panel px-4 py-3 text-left text-[13px] text-fg-2 shadow-card transition-colors hover:border-line-strong hover:text-fg">
                    {e}
                  </button>
                ))}
              </div>
            </div>
          ) : (
            <div className="space-y-6">
              {msgs.map((m, i) =>
                m.role === "user" ? (
                  <div key={i} className="flex justify-end">
                    <div className="max-w-[80%] rounded-2xl rounded-br-md bg-panel-3 px-4 py-2.5 text-[14px]">{m.content}</div>
                  </div>
                ) : (
                  <div key={i}>
                    <div className="text-[14px] leading-[1.7]">
                      {m.content ? <Answer text={m.content} sources={m.sources ?? []} onCite={openSource} /> : m.streaming ? <span className="text-fg-3">Reading the regulations…</span> : null}
                      {m.streaming && m.content && <span className="ml-0.5 inline-block h-4 w-1.5 animate-pulse bg-fg-3 align-middle" />}
                    </div>
                    {m.error && <div className="mt-2 text-[13px] text-red-text">{m.error}</div>}
                    {m.sources && m.sources.length > 0 && !m.streaming && (
                      <div className="mt-3 flex flex-wrap gap-1.5">
                        {m.sources.map((s) => (
                          <button key={s.n} onClick={() => openSource(s)} className="inline-flex items-center gap-1 rounded-md bg-panel px-2 py-0.5 text-[11.5px] text-fg-2 ring-1 ring-line hover:ring-line-strong" title={s.preview}>
                            <span className="font-mono text-fg-3">S{s.n}</span> {s.cite}
                          </button>
                        ))}
                      </div>
                    )}
                  </div>
                ),
              )}
              <div ref={bottom} />
            </div>
          )}
        </div>
      </div>
      <div className="border-t border-line bg-bg/80 backdrop-blur">
        <form
          className="mx-auto flex max-w-[820px] items-end gap-2 px-4 py-4 sm:px-8"
          onSubmit={(e) => {
            e.preventDefault();
            void ask(input);
          }}
        >
          <textarea
            value={input}
            onChange={(e) => setInput(e.target.value)}
            onKeyDown={(e) => {
              if (e.key === "Enter" && !e.shiftKey && !e.nativeEvent.isComposing) {
                e.preventDefault();
                void ask(input);
              }
            }}
            rows={1}
            placeholder="Ask about the EAR, the CCL or Japan’s export controls…"
            className="max-h-40 min-h-11 flex-1 resize-none rounded-xl border border-line-strong bg-panel px-4 py-2.5 text-[14px] shadow-sm outline-none focus:border-accent focus:ring-3 focus:ring-accent/15"
          />
          {busy ? (
            <button type="button" onClick={() => abort.current?.abort()} className="flex size-11 items-center justify-center rounded-xl bg-panel-3 text-fg" aria-label="Stop">
              <Square className="size-4" />
            </button>
          ) : (
            <button type="submit" disabled={!input.trim()} className="flex size-11 items-center justify-center rounded-xl bg-accent text-accent-fg disabled:opacity-40" aria-label="Send">
              <ArrowUp className="size-4" />
            </button>
          )}
        </form>
        <div className="mx-auto -mt-2 max-w-[820px] px-4 pb-3 text-[11px] text-fg-3 sm:px-8">
          <BookOpen className="mr-1 inline size-3" /> Research support grounded in the regulation text — not legal advice. <Badge tone="gray" className="ml-1">{meta.data?.settings.aiModel}</Badge>
        </div>
      </div>
    </div>
  );
}

/** Minimal markdown: paragraphs, bullets, bold, and [S#] citation chips. */
function Answer({ text, sources, onCite }: { text: string; sources: Source[]; onCite: (s: Source) => void }) {
  const blocks = text.split(/\n{2,}/);
  const inline = (s: string) =>
    s.split(/(\[S\d+(?:,\s*S\d+)*\]|\*\*[^*]+\*\*)/g).map((part, i) => {
      const cite = part.match(/^\[(S\d+(?:,\s*S\d+)*)\]$/);
      if (cite)
        return cite[1].split(/,\s*/).map((id) => {
          const src = sources.find((x) => `S${x.n}` === id);
          return (
            <button key={`${i}-${id}`} onClick={() => src && onCite(src)} title={src?.cite} className="mx-0.5 inline-flex h-[18px] items-center rounded bg-accent-soft px-1 align-[1px] font-mono text-[10.5px] font-medium text-accent-text hover:bg-accent hover:text-accent-fg">
              {id}
            </button>
          );
        });
      if (/^\*\*[^*]+\*\*$/.test(part)) return <strong key={i}>{part.slice(2, -2)}</strong>;
      return <Fragment key={i}>{part}</Fragment>;
    });
  return (
    <div className="space-y-3">
      {blocks.map((b, i) => {
        const lines = b.split("\n");
        if (lines.every((l) => /^\s*([-*•]|\d+\.)\s/.test(l)))
          return (
            <ul key={i} className="space-y-1 pl-1">
              {lines.map((l, j) => (
                <li key={j} className="flex gap-2">
                  <span className="mt-[11px] size-1 shrink-0 rounded-full bg-fg-3" />
                  <span>{inline(l.replace(/^\s*([-*•]|\d+\.)\s/, ""))}</span>
                </li>
              ))}
            </ul>
          );
        if (/^#{1,4}\s/.test(b)) return <div key={i} className={cx("font-semibold")}>{inline(b.replace(/^#{1,4}\s/, ""))}</div>;
        return <p key={i}>{inline(b)}</p>;
      })}
    </div>
  );
}
